# this docker-compose.yml is for developmental purposes only
version: '3.1'
services:
  db:
    container_name: cryptic_dev_mysql_1
    image: mysql
    restart: always
    environment:
        MYSQL_USER: cryptic
        MYSQL_PASSWORD: YOUR_PASSWORD  # TODO pick a secure password
        MYSQL_DATABASE: cryptic
        MYSQL_RANDOM_ROOT_PASSWORD: 1
  s_user:
    container_name: cryptic_dev_user_1
    restart: always
    build: .
    ports:
        - "1240:1240"
    links:
        - db
    depends_on:
        - db
    environment:
        MYSQL_HOSTNAME: "db"
        MYSQL_DATABASE: cryptic
        MYSQL_USERNAME: cryptic
        MYSQL_PASSWORD: YOUR_PASSWORD  # TODO adjust this line
        DEBUG: 1